server:
  port: 8030

spring:
  application:
    name: cloud-nas-websocket
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  data:
    redis:
      host: 122.152.237.135
      port: 6379

minio:
  endpoint: http://122.152.237.135:9000       # MinIO 服务地址（换成你的服务器IP）
  accessKey: minioadmin                       # 你设置的账号
  secretKey: minioadmin                   # 你设置的密码
  bucketName: cloud-nas