server:
  port: 8020

spring:
  datasource:
    username: root
    password: hdstartY@123@
    url: jdbc:mysql://122.152.237.135:3306/cloud_nas_admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: cloud-nas-admin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

minio:
  endpoint: http://47.109.93.230:9000        # MinIO 服务地址（换成你的服务器IP）
  accessKey: hdstartY                       # 你设置的账号
  secretKey: Ctbu@909703@                   # 你设置的密码
  bucketName: cloud-nas