server:
  port: 8080

spring:
  datasource:
    username: root
    password: hdstartY@123@
    url: jdbc:mysql://122.152.237.135:3306/cloud-nas-member?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: cloud-nas-member
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


  data:
    redis:
      host: 122.152.237.135
      port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

  #logging:
#  level:
#    com.baomidou.mybatisplus: debug
#    org.hdstart.cloud.mapper: debug # mapper 所在的包

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
minio:
  preUrl: http://122.152.237.135:9000
  endpoint: http://122.152.237.135:9000        # MinIO 服务地址
  accessKey: minioadmin                       # 账号
  secretKey: minioadmin                   # 密码
  bucketName: cloud-nas
